mysql:
  host: ${MYSQL_HOST:localhost}
  port: ${MYSQL_PORT:3306}
  username: ${MYSQL_USER:root}
  password: ${MYSQL_PASS:}
  db: ${MYSQL_DB:zipkin}
zipkin:
  store:
    type: ${STORAGE_TYPE:mem}
server:
  port: ${QUERY_PORT:9411}
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${mysql.host}:${mysql.port}/${mysql.db}?autoReconnect=true
    username: ${mysql.username}
    password: ${mysql.password}
    schema: classpath:/mysql.sql
# Switch this on to create the schema on startup:
    initialize: false
