language: java
sudo: false

services:
  - redis-server

jdk:
  - oraclejdk7
  - oraclejdk8

# These directories are cached to S3 at the end of the build
cache:
  directories:
    - $HOME/.gradle/wrapper
    - $HOME/.gradle/native
    - $HOME/.gradle/daemon
    - $HOME/.gradle/caches/jars-1
    - $HOME/.gradle/caches/2.5

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/637e968b45032d16ee26
    on_success: change
    on_failure: always
    on_start: false

env:
  global:
  - secure: G7Uwb8U5RGKc6qCCD6xUKPG5nncICq0NXuEPgl3bTRs8VQnYjcUJZLkMTl2tBFFZQii2f7EWpVOR/pDwMLDA3QDA05BL9WKLNbWKsjuy/LnxFT9NrHzRjV5Y64HymAwGjolqXxaqyATIJYzQuNti1DtfGOd0bEsPKaSwXTp1U3I=
  - secure: f9cm4ONRFVyaRsMMArvtsmzZPA7fQ0sH/gXzuew8Cg6HR5gHp02yfC9WHUHzvOlG/n18e0JqVh7WcymtjEocOsPvo+VNuDKKTU4/XIHJg4Tmy0/NiV2mEyXjGGm2fnrqshSzhlNbhKnwG0fInEyzSSgX710S8u5Ccp/T1AhcSuY=
  - secure: mLUlysAPQvd14VcOoaT5xjPANa6dNQQASm9KqYEvozDtDGRHEmsKEVo0pj5CCOe/ObUNS6m35vU6lW2Iziyw8+dfsl3CdLVkwRNMS8/mFvR1dvvKWWji0eGDoyt9p2Mcqh9YhrSVKl6X51tA7QMCHeOKyOBcu/87GaE3XQzmkOQ=
  - secure: Zlj8xYEB6oGMyI1PiexdRxm+RZwMtpNEBMUkxniZbAm5RFmLLwU4YWd4MlEr0TqRjS/lPYcVRYCVSb0nCYimrxzEhemT9MbYx90wm7XFT5v61OMGYgvghDYtxiIosXqidKbOtOWoxgKHcEP1g9r/fbx2hUG3Nn+1Sx81eW9FeUQ=
  - secure: gAHGAUcBubm4MVf5ZNBwq7y4hYrakBELp917r+Pgd5fTF6NovFvTe/yCHXfGdRI9T4ocp4hdHn/l0AxRCyJX9LTyZqaOvVwuxn091Tmga3Y5kJpiIBQZ0GHlAfiN7cHhwvJtQWdzB+nVAM5ZtiemVdEkVVsqR1XUR81KqV9B1zg=

before_install:
  - git config --global user.email "${GH_USER_EMAIL}"
  - git config --global user.name "${GH_USER}"

before_script:
  - git remote set-url origin "https://${GH_TOKEN}@github.com/openzipkin/zipkin.git"

after_success: ./travis/publish.sh
