language: java
sudo: false

services:
  - redis-server

jdk:
  - oraclejdk7
  - oraclejdk8

# These directories are cached to S3 at the end of the build
cache:
  directories:
    - $HOME/.gradle/wrapper
    - $HOME/.gradle/native
    - $HOME/.gradle/daemon
    - $HOME/.gradle/caches/jars-1
    - $HOME/.gradle/caches/2.5

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/637e968b45032d16ee26
    on_success: change
    on_failure: always
    on_start: false

env:
  global:
  - secure: YfOFIa0ImvS66G43A9lYKzKZe6b/c4zsnSQvVOtQ+p2i4jz+q54ArmaojwT/aejnattf0tixCWAaXBef2GPMOICXVgxP+IpOOli2nJv4i1GcUY0RsZSz3Z01UXA/v7984/FrAUfFJ/xVvMz1X1OJoRRHb8G16NKY0lGkLFEL3h3FpjSsESYs+JGAoxMcjW/HExzJxD3k7PzE42ijkrZ/DBNMn+0aLhLPyibS7mNv94/anJtoogqSeKuxWjx5GK1M2yjYb+2WkibMbaXmxVwdUTkeHbi553yKzCc12Oxwutx1Wtu9qZ43E9nRYpurOsohbFI2GsjANTbsthKwN7eHHdiIMAn6ttR6O1AlrA5AMi6E3L5ypwawI4zqbPouNfGuL1FWJtYYqGNhbuMuSQWP4nEe5B0GM0/7+e0gBjlGunpNy85Uzg0oqqUAI1HZxqYqL9B3OuoEDUbJudo5BI3Q/3b5HcEL0SI9dVXn4HDtt2H6RlGrC6MXJ8mpCflrI09GadFec4t4wGgQZFi3jB+yxqmbdzkRANpdTRlme1YEaLe5mqtw42l0yjwUsfKfk2i6r0bxt5hKz9P2ZwUFG5+DIh7A36hnGfGlmO0ldfZ2S1EXlbvy4OfWFG76+7tfiCDsuueephXmk6jW0ZoLWDQyjLe7qsLtnzY3Vdwxcja8Mug=
  - secure: 0c7xZ3iITP8JNRjAHu6NoCsuU6Xs3L3P4ff8ZOuDUrc44NZUwLxbbMnSvUzoqedvf/EPgBfOcHA1clSKvyDp98g4tPehcWa1tDHf7tSr7dqbw+klFRsRbobu0PTNQS1tO90DKtEfcYhm6eyqXqY6IX+ibIBUQFhKz6RC8mkopMy+DazkAr3/eIBrSA3OWgT8XpxYNRPDbq1sbHDRlbRJ1ZRbqFzsbupG+uNa2TqOabbxBP8EMMfvYkGdgVCRtjZ+n31DS34ZxIojBXMK8OgnzA1i98zJj7nMobHu4DzQdGQXZxtGEitL6R5YeT4peeLbfKyHdLJp7GEvICoqJQij/N4xTFUL3C6gJeCOZmqUpz0c3HQHuMYzRYiZeTpsRVeYw7T2SZV3ervOC1ARb6gFkd55J/SY/HcsHhjM7cZDE4cwzaIPYTZ+XHApGqCGeIaXpXrZYuJ5fHo3DdtmMmVJGD0e7R6zPi076GKvhoLA6b3njGKsXtNDUJwf6VoMMHQS8vFFsgL4OBN+hrnc4ZbYSuUISWdOjooRAWSO6oyd2x7LA4vS1fxEDpis4uZunZXGWHLEpnOcvFQSNrOjXvtJW6Ikm4HCl4fuHa0KjiJbe7THLD9vxCR4XfDLfc5/LP3kT/89BfannTP5ttnbgzkJrSXpZRaamDaXJg51n3dZ2YQ=
  - secure: CMCslJfwDxnFOuHdQplC3xgYpPbX5CadMxSxNpZCWQ/wLk2d8gQgda62CDi9RzJrNtdITg1hHaAbZZJLqLYHYamNYAFHf1KcEsj9nMMfQ+e53lyhNiuA1j803zwZkeoWPdDrxyRG5ps4lz36Lo1FQkYcvgsqo0XTH3bgSHTnWVovAWM7o1vL9RDcgAg+gvVVDRiUOuioPYlRzRo8t3sLOnHoZ2e0h1qyn35BQMJfO4B8e7nDqNtlFSTUkK4i5koGBP3IUXVKQJAea6EEXD6ZdqzmHta8Y1WxJn0YZSwa+/OKueWpBts7992TOlG5n0UgS0ot31EQH1x4pQgSIPoHIyxNn1LXHWkxELkz8KgHfNo/6jj6V3BLhocifbMyx3tSQSSsJKnvwXaBxnjFzyOihZo8/1GOInDm6RmLNpZNqBxACgR2yOyJXrWJKNC4ZJKhPla5ER1CqNQLb1FxosYvIz07r8nUPYJvLLHFp8ToUT/R8ms66TF0H+X6l/wNkvuVbEX5AlhvBhFYfPUcBmGuVNzJ39w332LbfJgiuGTJ0ZM7aBrl5TSFIK9aThyrwKhQlyvtqXMrhxD8R5DPUfi6iGH3hefomzptVXzyu9MPM5sjelqeBaaXpKSlzYOUz8OonCMWqpu/PfeY2e4CWYRLxUkN5Rk8vW3ZgZwkgdzWE+c=
  - secure: ErKb7y3VK6a0IJT6+lPpTqN2vI6vhHpcLGIP7eRfMWlxpTs15TPvExmveUuThqqjZJ0OW0lkkRXImGI6WDmjvcsRAr+qv71rOTmBUmeOTefIu0mpQBc8bH2/1y3xjYhQCsnaVd2T6M38IwSja8ZtE/Oh/x4wSjmjgHk+rMc38lv+kDqaMCvWLjVECwnWjo30oHnzUs5Z+3NWffIT8V0KjhDp3SJOAn9SXvlNU+cmnPLFEOLh3ztIPvNwVn4Z6Kwakya5IRLWOynNI6NrS1j9F5smuTs3nVwUTi3oLCZEiNJFkrii1XrKFZAOyT7OzIk6zwOAJMKDx6usnRYvLeCc4znPYddt9cbHv8RPHVPhGN+i0e54Ug5oGxoIsz0BjqSsnUM8usO4YQvS9lp7LjGOTEU4uX3T4E9uqEijEzJkAaNWHY5xVNV6QqjuX2ckxIXeVzj814Ozi57OmH0nk0x0RkOGarp+Sm6Y1qBClROjjw6ls4AaZMfH63pkYWQUti8loEJpQiKvsR/oCeHPui3rEfkV90diKSWKE9IfIbAqUuXl0m8j1OpOVUDxUBQkwv54ddibKeccu8IkYsLczx1CdZRs/PkrblR1jj7jn/uyu2LUDyLGxyoWgG1FVtsWi09LR0PR8XJEJ3wyn04acxR1EfWaGJgTJGgv4RQwWfSAhUw=
  - secure: rbOuhqc4Cxqp76B0UnR8lNh5viabh8HNUk2r5xnP7RVG7OaJXwRHtkpQKffM0HztyC2loxDbhvL3Z/0DjweBD9dmT4A6gBK6fhhVDaWdfaVAAoKIW9HS6DFhJT2rWE4EXgQR39Hc+mEAjIOqCcZt7dDjJUcF9vwOBN3Gsno9o78sWjaPhp/Yqo3wPsb2jQPEoGd0ZW4/0/RvC+4EZ5BgelBAIiqVMIMIdoy99M3euHy5EvSMWB9uKbzyoGNt/nkQxlptrONvtdh2XwcGllxoHWSYRI5k+CKFDLOtDuGT1lFkxb2S5KIVAH1HsVAYOpAuVxn8oXi//s4b9llmsUTFJGs8dgYwPtoKglyrSMpr9baPf5utxSE6/1F+2v/z0KfQVGAD9yWLbp6RROLfILXyaLZZxIacGAoH1s+wDGcIgU6meS5q6N2UG39Y831U/Qi3c3r+W1e1fN6/pjFe96Z1H+fISd1fi8CTqgbxx80N6daon66ijqeyb9xxz3Rm4381BK5OdiOALCNEzWhX+fYJCaaKR0LzkyZrEcfqJqBK48OMTNpM5+7bNPB4x6fls1pam9OUu8o4J1cMphIqXP+PQqtvf0cnZ+k4KLmCUCb4vdieBYTbVkGdYisVHoq5qVTsZE58ZfL+Y/DIoZz6LbSeWK2rdKCZBD/Rcrz8XlkD83A=

before_install:
  - git config --global user.email "${GH_USER_EMAIL}"
  - git config --global user.name "${GH_USER}"

before_script:
  - git remote set-url origin "https://${GH_TOKEN}@github.com/openzipkin/zipkin.git"

after_success: ./travis/publish.sh
